export interface SeedProduct {
  id: string;
  storeId: string;
  name: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  costPrice: number;
  stock: number;
  images: string[];
  features: string[];
  specifications?: Record<string, any>;
  tags: string[];
  status: 'PUBLISHED' | 'DRAFT' | 'LOW_STOCK';
}

export const DEMO_MERCHANT = {
  id: 'merchant-opticommerce-001',
  name: 'OptiCommerce Demo Merchant',
  email: 'merchant@opticommerce.io',
  passwordHash: '$2b$10$JDjiAs6jumJe0HLZy4LFIeGrGZ7sWzcS1GU8J9rvPVALp8vuFoSCe', // Merchant@2026
};

export const DEMO_STORE = {
  id: 'store-opticommerce-001',
  merchantId: 'merchant-opticommerce-001',
  name: 'OptiCommerce Flagship Electronics',
  slug: 'opticommerce-flagship-electronics',
  description: 'Flagship online electronics and smart devices storefront powered by AI margin optimization.',
  status: 'PUBLISHED' as const,
};

const storeId = DEMO_STORE.id;

export const INITIAL_100_PRODUCTS: SeedProduct[] = [
  // --- 15 REALISTIC CATALOG PRODUCTS (prod-001 to prod-015) ---
  {
    id: 'prod-001',
    storeId,
    name: 'SoundCore Space One Hybrid ANC Wireless Headphones',
    description: 'Over-ear active noise cancelling wireless headphones with 2x stronger voice reduction, 40h ANC playtime, and LDAC Hi-Res audio.',
    category: 'Audio',
    brand: 'Soundcore',
    price: 4499,
    costPrice: 2600,
    stock: 32,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'],
    features: ['Hybrid Active Noise Cancelling', '40h ANC Battery Life', 'LDAC Hi-Res Audio Certified', 'Custom EQ App'],
    tags: ['headphones', 'wireless', 'over-ear', 'anc', 'audio', 'noise cancelling', 'bluetooth'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-002',
    storeId,
    name: 'JBL Tune 760NC Wireless Over-Ear NC Headphones',
    description: 'Lightweight foldable over-ear headphones with active noise cancelling, JBL Pure Bass sound, and 35h battery with quick charge.',
    category: 'Audio',
    brand: 'JBL',
    price: 4999,
    costPrice: 2900,
    stock: 28,
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80'],
    features: ['Active Noise Cancelling', 'JBL Pure Bass Sound', '35 Hours Battery with BT+NC', 'Hands-Free Multi-Point Connection'],
    tags: ['headphones', 'wireless', 'anc', 'jbl', 'pure bass', 'audio', 'over-ear'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-003',
    storeId,
    name: 'Audio-Technica ATH-M20xBT Wireless Studio Headphones',
    description: 'Critically acclaimed M-Series studio sound tuned for enhanced low-frequency performance with 60-hour wireless battery life.',
    category: 'Audio',
    brand: 'Audio-Technica',
    price: 4899,
    costPrice: 2800,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80'],
    features: ['40mm Rare Earth Neodymium Drivers', '60 Hours Battery Life', 'Low Latency Gaming/Video Mode', 'Multipoint Bluetooth Pairing'],
    tags: ['headphones', 'studio', 'wireless', 'audio-technica', 'monitor', 'audio', 'over-ear'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-004',
    storeId,
    name: 'Dell XPS 15 InfinityEdge Business Laptop',
    description: 'High-performance 15.6-inch 3.5K OLED touchscreen laptop powered by Intel Core i7 13th Gen, 32GB DDR5 RAM, and RTX 4060 graphics.',
    category: 'Computing',
    brand: 'Dell',
    price: 145990,
    costPrice: 112000,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80'],
    features: ['15.6" 3.5K OLED Touchscreen', 'Intel Core i7-13700H', 'NVIDIA GeForce RTX 4060', 'CNC Aluminum Chassis'],
    tags: ['laptop', 'dell', 'xps', 'workstation', 'creator', 'computing', 'intel'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-005',
    storeId,
    name: 'HP Pavilion Plus 14 OLED Ultraportable Laptop',
    description: 'Sleek 14-inch 2.8K 120Hz IMAX Enhanced OLED laptop with AMD Ryzen 7 7840U, 16GB LPDDR5x RAM, and all-day battery life.',
    category: 'Computing',
    brand: 'HP',
    price: 78999,
    costPrice: 58000,
    stock: 16,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80'],
    features: ['14" 2.8K 120Hz OLED Display', 'AMD Ryzen 7 7840U 8-Core', '16GB LPDDR5x RAM', 'Backlit Keyboard & Wi-Fi 6E'],
    tags: ['laptop', 'hp', 'oled', 'ultraportable', 'thin and light', 'computing', 'ryzen'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-006',
    storeId,
    name: 'ASUS ROG Zephyrus G14 Gaming Laptop',
    description: 'Ultra-compact 14-inch gaming beast featuring ROG Nebula 3K 120Hz OLED display, AMD Ryzen 9 8945HS, and NVIDIA RTX 4060.',
    category: 'Gaming',
    brand: 'ASUS',
    price: 124990,
    costPrice: 95000,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80'],
    features: ['ROG Nebula 3K 120Hz OLED', 'AMD Ryzen 9 8945HS with AI Engine', 'NVIDIA GeForce RTX 4060 8GB', 'Slash Lighting Aluminum Lid'],
    tags: ['laptop', 'gaming laptop', 'asus', 'rog', 'zephyrus', 'gaming', 'rtx 4060'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-007',
    storeId,
    name: 'Logitech M331 Silent Plus Wireless Mouse',
    description: 'Ergonomic right-handed wireless optical mouse with 90% sound reduction silent clicks and 24-month battery life.',
    category: 'Accessories',
    brand: 'Logitech',
    price: 1395,
    costPrice: 680,
    stock: 65,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['SilentTouch 90% Click Noise Reduction', '24-Month Single AA Battery Life', 'Curved Rubber Grips', '1000 DPI Optical Tracking'],
    tags: ['mouse', 'wireless mouse', 'silent mouse', 'logitech', 'accessories', 'ergonomic'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-008',
    storeId,
    name: 'Rapoo MT750L Multi-Device Ergonomic Wireless Mouse',
    description: 'Precision ergonomic laser mouse with side thumb scroll wheel, Bluetooth 4.0/2.4GHz tri-mode connection, and 3200 DPI.',
    category: 'Accessories',
    brand: 'Rapoo',
    price: 1899,
    costPrice: 920,
    stock: 42,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80'],
    features: ['Multi-Device Easy Switch (Up to 4 devices)', 'Side Thumb Scroll Wheel', 'Adjustable 3200 DPI Laser Engine', 'USB Rechargeable Lithium Battery'],
    tags: ['mouse', 'wireless mouse', 'ergonomic mouse', 'multi-device', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-009',
    storeId,
    name: 'Samsung Galaxy S24 5G AI Smartphone (128GB)',
    description: 'Flagship 6.2-inch FHD+ Dynamic AMOLED 2X 120Hz display with Galaxy AI, 50MP ProVisual Engine triple camera, and Armor Aluminum frame.',
    category: 'Mobile',
    brand: 'Samsung',
    price: 74999,
    costPrice: 56000,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80'],
    features: ['Galaxy AI Live Translate & Circle to Search', '6.2" Dynamic AMOLED 2X 120Hz', '50MP Triple Camera System', 'IP68 Water & Dust Resistance'],
    tags: ['smartphone', 'mobile', 'samsung', 'galaxy', '5g', 'galaxy s24', 'phone'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-010',
    storeId,
    name: 'Anker Nano 30W USB-C GaN Fast Charger',
    description: 'Ultra-compact foldable 30W GaN wall charger capable of high-speed charging phones, tablets, and MacBook Air.',
    category: 'Accessories',
    brand: 'Anker',
    price: 1499,
    costPrice: 720,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['30W GaN Power Delivery Output', '70% Smaller Than Original 30W Charger', 'ActiveShield 2.0 Temperature Monitoring', 'Foldable Travel Prongs'],
    tags: ['charger', 'fast charger', 'anker', 'gan', 'usb-c', 'accessories', 'power adapter'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-011',
    storeId,
    name: 'UGREEN Revodok 7-in-1 4K HDMI USB-C Hub',
    description: 'Aluminum multiport adapter with 4K@60Hz HDMI output, 100W PD pass-through charging, 2x USB 3.0, and SD/TF card slots.',
    category: 'Accessories',
    brand: 'UGREEN',
    price: 2199,
    costPrice: 1050,
    stock: 55,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['4K @ 60Hz Ultra HD HDMI Output', '100W Pass-Through Power Delivery', '5Gbps Dual USB 3.0 Ports', 'Aluminum Heat-Dissipating Casing'],
    tags: ['usb-c hub', 'docking station', 'ugreen', 'hdmi adapter', 'accessories', 'usb hub'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-012',
    storeId,
    name: 'Spigen Ultra Hybrid Frosted Case for iPhone 15',
    description: 'Anti-yellowing hybrid case with shock-absorbent TPU bumper, clear PC back, and Air Cushion technology for drop defense.',
    category: 'Accessories',
    brand: 'Spigen',
    price: 1299,
    costPrice: 540,
    stock: 70,
    images: ['https://images.unsplash.com/photo-1601593346740-925612772716?w=800&auto=format&fit=crop&q=80'],
    features: ['Air Cushion Technology Drop Defense', 'Anti-Yellowing Polycarbonate Back', 'Raised Camera Bezel & Screen Lips', 'Wireless Charging Compatible'],
    tags: ['phone case', 'iphone case', 'spigen', 'protective cover', 'accessories', 'case'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-013',
    storeId,
    name: 'Spigen GlasTR EZ FIT Tempered Glass Screen Guard',
    description: 'Premium 9H hardness tempered glass with auto-alignment installation tray and oleophobic smudge-resistant coating.',
    category: 'Accessories',
    brand: 'Spigen',
    price: 999,
    costPrice: 380,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=80'],
    features: ['EZ FIT Auto-Alignment Installation Tray', '9H Surface Hardness Durability', 'Oleophobic Anti-Fingerprint Layer', 'Crystal Clear Touch Sensitivity'],
    tags: ['screen protector', 'tempered glass', 'spigen', 'screen guard', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-014',
    storeId,
    name: 'Tomtoc 360 Defender 14" Spill-Resistant Laptop Sleeve',
    description: 'Military-spec drop-tested laptop protective sleeve featuring CornerArmor patent tech, high-density fleece interior, and YKK zippers.',
    category: 'Accessories',
    brand: 'Tomtoc',
    price: 2299,
    costPrice: 1100,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80'],
    features: ['CornerArmor Patent Drop Protection', 'Spill-Resistant Recycled Fabric', 'Soft Fluffy Interior Fleece Padding', 'Front Zippered Organizer Pocket'],
    tags: ['laptop sleeve', 'laptop bag', 'tomtoc', 'protective sleeve', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-015',
    storeId,
    name: 'Sony Alpha A6700 APS-C Mirrorless Camera Body',
    description: 'Next-generation 26.0MP back-illuminated Exmor R CMOS sensor with dedicated AI processing unit for real-time subject tracking and 4K 120p video.',
    category: 'Electronics',
    brand: 'Sony',
    price: 136990,
    costPrice: 105000,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80'],
    features: ['26.0MP BSI Exmor R CMOS Sensor', 'AI-Powered Real-Time AF Tracking', '4K 120p High Frame Rate Video', '5-Axis Optical In-Body Stabilization'],
    tags: ['camera', 'mirrorless', 'sony', '4k video', 'photography', 'electronics'],
    status: 'PUBLISHED',
  },

  // --- AUDIO (prod-016 to prod-028) ---
  {
    id: 'prod-016',
    storeId,
    name: 'ZenWave Pro ANC Wireless Earbuds',
    description: 'Active noise cancelling true wireless earbuds with 32-hour total battery, transparency mode, and spatial audio.',
    category: 'Audio',
    brand: 'ZenAudio',
    price: 3999,
    costPrice: 2100,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80'],
    features: ['Hybrid Active Noise Cancelling', '32h Playtime Case', 'IPX5 Water Resistant', 'Wireless Charging'],
    tags: ['earbuds', 'wireless earbuds', 'tws', 'anc', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-017',
    storeId,
    name: 'EchoBeat Sport TWS Earbuds',
    description: 'Ergonomic in-ear wireless sport earbuds with secure wingtips, sweatproof nano-coating, and punchy bass drivers.',
    category: 'Audio',
    brand: 'EchoBeat',
    price: 4499,
    costPrice: 2400,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80'],
    features: ['Secure Fit Earhooks', 'IPX7 Waterproof Rating', 'Punchy Sub-Bass Sound', '30h Playtime'],
    tags: ['earbuds', 'wireless earbuds', 'sports earbuds', 'audio', 'tws'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-018',
    storeId,
    name: 'AcousticPure Studio Wireless Earbuds',
    description: 'Hi-Res certified wireless earbuds with dual balanced armature drivers and LDAC lossless codec.',
    category: 'Audio',
    brand: 'AcousticPure',
    price: 5499,
    costPrice: 3200,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80'],
    features: ['Hi-Res LDAC Audio Codec', 'Dual Knowles Armature Drivers', 'Multipoint Bluetooth 5.3'],
    tags: ['earbuds', 'wireless earbuds', 'audiophile', 'hi-res', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-019',
    storeId,
    name: 'Bose QuietComfort 45 Over-Ear',
    description: 'Legendary noise cancelling headphones with TriPort acoustic architecture, plush earcups, and crystal clear call mics.',
    category: 'Audio',
    brand: 'Bose',
    price: 26900,
    costPrice: 19500,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80'],
    features: ['Acoustic Noise Cancelling', '24h Battery on Single Charge', 'TriPort Acoustic Architecture'],
    tags: ['headphones', 'premium headphones', 'over-ear', 'bose', 'anc'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-020',
    storeId,
    name: 'Sennheiser Momentum 4 Wireless',
    description: 'Audiophile-grade 42mm transducer system delivering incredible dynamics with 60-hour battery life.',
    category: 'Audio',
    brand: 'Sennheiser',
    price: 34990,
    costPrice: 25000,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'],
    features: ['60-Hour Class-Leading Battery', '42mm Audiophile Transducer', 'Adaptive Noise Cancellation'],
    tags: ['headphones', 'premium headphones', 'sennheiser', 'audiophile', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-021',
    storeId,
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise cancellation powered by two processors and eight microphones with auto NC optimizer.',
    category: 'Audio',
    brand: 'Sony',
    price: 29990,
    costPrice: 22000,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80'],
    features: ['Integrated Processor V1 & QN1', 'Auto NC Optimizer', 'Speak-to-Chat Technology'],
    tags: ['headphones', 'premium headphones', 'sony', 'anc', 'wireless'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-022',
    storeId,
    name: 'SoundBoom 360 Portable Bluetooth Speaker',
    description: 'Compact IPX7 waterproof wireless outdoor speaker with 360-degree room-filling acoustic audio and 16h playtime.',
    category: 'Audio',
    brand: 'SoundBoom',
    price: 3499,
    costPrice: 1800,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'],
    features: ['360-Degree Omnidirectional Sound', 'IPX7 Waterproof', '16-Hour Playtime', 'Party Duo Link'],
    tags: ['speakers', 'speaker', 'bluetooth speaker', 'audio', 'portable'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-023',
    storeId,
    name: 'Harman Kardon Aura Studio 4',
    description: 'Iconic dome speaker design with ambient diamond lighting and 130W multi-directional room sound.',
    category: 'Audio',
    brand: 'Harman Kardon',
    price: 24999,
    costPrice: 17500,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'],
    features: ['130W Powerful Sound', 'Ambient Diamond Lighting Effect', '5.1 Channel Soundstage'],
    tags: ['speakers', 'speaker', 'home audio', 'premium', 'harman kardon'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-024',
    storeId,
    name: 'JBL Flip 6 Waterproof Portable Speaker',
    description: '2-way speaker system delivering loud, crystal clear audio with deep punchy bass and IP67 water/dust resistance.',
    category: 'Audio',
    brand: 'JBL',
    price: 9999,
    costPrice: 6800,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'],
    features: ['2-Way Speaker System', 'IP67 Dust and Waterproof', '12h Playtime', 'PartyBoost Mode'],
    tags: ['speakers', 'speaker', 'jbl', 'bluetooth speaker', 'waterproof'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-025',
    storeId,
    name: 'Rode PodMic Dynamic Broadcast Microphone',
    description: 'Broadcast-quality dynamic cardioid microphone optimized for podcasting, streaming, voiceover, and studio recording.',
    category: 'Audio',
    brand: 'Rode',
    price: 11490,
    costPrice: 8200,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80'],
    features: ['Cardioid Pickup Pattern', 'Internal Pop Filter', 'All-Metal Construction', 'XLR Output'],
    tags: ['microphones', 'microphone', 'podcast', 'streaming', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-026',
    storeId,
    name: 'HyperX QuadCast S RGB USB Condenser Mic',
    description: 'USB microphone with customizable dynamic RGB lighting, anti-vibration shock mount, and four polar patterns.',
    category: 'Audio',
    brand: 'HyperX',
    price: 13990,
    costPrice: 9800,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80'],
    features: ['Customizable RGB Lighting', 'Anti-Vibration Shock Mount', 'Tap-to-Mute Sensor with LED', '4 Polar Patterns'],
    tags: ['microphones', 'microphone', 'usb mic', 'gaming', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-027',
    storeId,
    name: 'AcousticShield Mic Pop Filter & Boom Arm',
    description: 'Heavy-duty adjustable microphone boom arm with dual-layer nylon pop filter and desk clamp.',
    category: 'Accessories',
    brand: 'AcousticShield',
    price: 1699,
    costPrice: 700,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Adjustable Suspension Arm', 'Dual Layer Pop Screen', 'Standard 3/8" to 5/8" Adapter'],
    tags: ['boom arm', 'pop filter', 'microphone stand', 'accessories', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-028',
    storeId,
    name: 'ZenAudio Gold Plated 3.5mm Aux Cable (2m)',
    description: 'Braided nylon oxygen-free copper 3.5mm male-to-male auxiliary audio cable with 24K gold plated jacks.',
    category: 'Accessories',
    brand: 'ZenAudio',
    price: 449,
    costPrice: 120,
    stock: 120,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['24K Gold-Plated Connectors', 'Oxygen-Free Copper Core', 'Tangle-Free Braided Nylon'],
    tags: ['aux cable', 'audio cable', 'cables', 'accessories', 'headphone cable'],
    status: 'PUBLISHED',
  },

  // --- LAPTOPS & COMPUTING (prod-029 to prod-043) ---
  {
    id: 'prod-029',
    storeId,
    name: 'AeroBook Air 14" Thin & Light Laptop',
    description: 'Intel Core i5 13th Gen, 16GB LPDDR5 RAM, 512GB NVMe SSD, 1.2kg ultralight chassis, 14" FHD IPS display for office and college.',
    category: 'Computing',
    brand: 'AeroBook',
    price: 64999,
    costPrice: 48000,
    stock: 16,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80'],
    features: ['1.2kg Magnesium Alloy Chassis', '14" 100% sRGB FHD Display', '14 Hours Battery Life', 'Backlit Keyboard'],
    tags: ['laptop', 'laptops', 'ultrabook', 'college laptop', 'computing'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-030',
    storeId,
    name: 'ThinkPro Workstation 15.6" Laptop',
    description: 'Intel Core i7 14th Gen, 32GB RAM, 1TB SSD, NVIDIA RTX 4050 6GB GPU, designed for engineers and programmers.',
    category: 'Computing',
    brand: 'ThinkPro',
    price: 94999,
    costPrice: 72000,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80'],
    features: ['Intel Core i7-14700H', '32GB DDR5 5600MHz', 'NVIDIA RTX 4050 6GB', 'Military-Grade Durability'],
    tags: ['laptop', 'laptops', 'workstation', 'programmer laptop', 'computing'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-031',
    storeId,
    name: 'Predator Legion 16" Gaming Laptop',
    description: 'AMD Ryzen 9 7940HS, RTX 4070 8GB, 32GB RAM, 1TB Gen4 SSD, 240Hz QHD G-Sync display with liquid metal cooling.',
    category: 'Gaming',
    brand: 'Predator',
    price: 149999,
    costPrice: 115000,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80'],
    features: ['16" 240Hz QHD Display', 'RTX 4070 8GB 140W TGP', 'RGB Per-Key Mechanical Keyboard'],
    tags: ['laptop', 'laptops', 'gaming laptop', 'gaming', 'computing'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-032',
    storeId,
    name: 'SwiftBook Slim 13.3" College Laptop',
    description: 'AMD Ryzen 5 7530U, 16GB RAM, 512GB SSD, all-day battery life and metal unibody for students and daily work.',
    category: 'Computing',
    brand: 'SwiftBook',
    price: 69999,
    costPrice: 52000,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80'],
    features: ['AMD Ryzen 5 6-Core', '16GB Dual-Channel RAM', 'Fast Fingerprint Sensor', '65W USB-C PD Charging'],
    tags: ['laptop', 'laptops', 'college laptop', 'students', 'computing'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-033',
    storeId,
    name: 'Logitech MX Master 3S Wireless Mouse',
    description: 'Quiet-click ergonomic performance wireless mouse with 8K DPI any-surface sensor and MagSpeed magnetic scrolling.',
    category: 'Accessories',
    brand: 'Logitech',
    price: 8995,
    costPrice: 6200,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['MagSpeed Electromagnetic Scroll', 'Quiet Click Switches', '8000 DPI Darkfield Sensor', 'Multi-Device Flow'],
    tags: ['mouse', 'wireless mouse', 'ergonomic mouse', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-034',
    storeId,
    name: 'Logitech MX Keys S Wireless Keyboard',
    description: 'Smart illuminated low-profile wireless productivity keyboard with spherically dished keys and dual Mac/Windows layout.',
    category: 'Accessories',
    brand: 'Logitech',
    price: 10495,
    costPrice: 7500,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['Smart Backlighting with Hand Proximity', 'Low Profile Tactile Keys', 'USB-C Rechargeable 5 Months'],
    tags: ['keyboard', 'wireless keyboard', 'productivity', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-035',
    storeId,
    name: 'Keychron K2 Pro Mechanical Wireless Keyboard',
    description: '75% compact QMK/VIA programmable wireless mechanical keyboard with hot-swappable Keychron K Pro red switches.',
    category: 'Accessories',
    brand: 'Keychron',
    price: 8499,
    costPrice: 5800,
    stock: 28,
    images: ['https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&auto=format&fit=crop&q=80'],
    features: ['Hot-Swappable Switches', 'QMK/VIA Open-Source Customization', 'Bluetooth 5.1 & Type-C Wired'],
    tags: ['keyboard', 'mechanical keyboard', 'wireless', 'accessories', 'computing'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-036',
    storeId,
    name: 'AlumaStand Ergonomic Aluminum Laptop Stand',
    description: 'Foldable aircraft-grade aluminum ventilated laptop riser stand with adjustable height and non-slip silicone pads.',
    category: 'Accessories',
    brand: 'AlumaStand',
    price: 1599,
    costPrice: 650,
    stock: 60,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['Aircraft-Grade Aluminum Alloy', '6 Adjustable Ergonomic Heights', 'Ventilated Hollow Heat Dissipation'],
    tags: ['laptop stand', 'stand', 'riser', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-037',
    storeId,
    name: 'FrostBreeze Dual-Fan Laptop Cooling Pad',
    description: 'Quiet dual 140mm fans with metal mesh top panel, adjustable incline angles, and dual USB pass-through ports.',
    category: 'Accessories',
    brand: 'FrostBreeze',
    price: 1899,
    costPrice: 850,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Dual 140mm Silent LED Fans', 'Metal Mesh Heat Dissipation', 'USB Pass-Through Port'],
    tags: ['cooling pad', 'laptop cooler', 'accessories', 'laptop', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-038',
    storeId,
    name: 'ClearCam 4K UHD Streaming Webcam',
    description: '4K 30fps / 1080p 60fps streaming webcam with Sony Starvis sensor, autofocus, privacy shutter, and stereo microphones.',
    category: 'Accessories',
    brand: 'ClearCam',
    price: 6499,
    costPrice: 4100,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['Sony 4K Starvis Sensor', 'Fast AI Autofocus', 'Integrated Privacy Shutter', 'Stereo Noise-Cancelling Mics'],
    tags: ['webcam', 'camera', 'streaming', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-039',
    storeId,
    name: 'ArmorPack 15.6" Shockproof Laptop Sleeve',
    description: 'CornerArmor patent technology with water-resistant fabric and thick plush lining to protect 15.6" laptops.',
    category: 'Accessories',
    brand: 'ArmorPack',
    price: 1499,
    costPrice: 580,
    stock: 55,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80'],
    features: ['CornerArmor Impact Defense', 'Water-Repellent Exterior', 'Soft Velvet Interior'],
    tags: ['laptop sleeve', 'sleeve', 'laptop bag', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-040',
    storeId,
    name: 'OmniPort 10-in-1 Dual Display USB-C Dock',
    description: 'Dual 4K HDMI, Gigabit Ethernet, 100W PD charging, 4x USB 3.2 Gen2, SD/TF card slots for laptop productivity.',
    category: 'Accessories',
    brand: 'OmniPort',
    price: 3999,
    costPrice: 2200,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Dual 4K Display Output', '100W Power Delivery Pass-Through', 'Gigabit RJ45 Ethernet Port'],
    tags: ['usb-c hub', 'usb hub', 'docking station', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-041',
    storeId,
    name: 'SwiftTouch Ergonomic Wireless Keyboard & Mouse Combo',
    description: 'Full-size spill-resistant wireless keyboard and 1600 DPI optical mouse with single 2.4GHz nano receiver.',
    category: 'Accessories',
    brand: 'SwiftTouch',
    price: 1799,
    costPrice: 850,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['Plug and Play 2.4GHz Receiver', 'Spill-Resistant Keyboard', '1600 DPI Mouse'],
    tags: ['keyboard', 'mouse', 'wireless mouse', 'accessories', 'combo'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-042',
    storeId,
    name: 'PrecisionGlide XL Desk Mat (900x400mm)',
    description: 'Water-resistant micro-woven cloth extended gaming and office desk pad with anti-fray stitched borders.',
    category: 'Accessories',
    brand: 'GlidePro',
    price: 899,
    costPrice: 320,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['900x400mm Extended Surface', 'Anti-Fray Precision Stitching', 'Non-Slip Natural Rubber Base'],
    tags: ['mouse pad', 'desk mat', 'accessories', 'office', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-043',
    storeId,
    name: 'ThunderCharge 100W USB-C Braided Cable (2m)',
    description: 'E-marker chip 100W 5A USB-C to USB-C cable supporting 480Mbps data transfer and fast laptop PD charging.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 699,
    costPrice: 210,
    stock: 100,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['100W 5A E-Marker Chip', 'Military Braided Outer Shield', '480Mbps Data Sync'],
    tags: ['usb-c cable', 'charging cable', 'cables', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },

  // --- MOBILE (prod-044 to prod-056) ---
  {
    id: 'prod-044',
    storeId,
    name: 'Pixel Ultra 5G AI Smartphone',
    description: 'Flagship Tensor G3 processor with computational photography, 6.7" OLED 120Hz display, and 7 years of OS updates.',
    category: 'Mobile',
    brand: 'Google',
    price: 79999,
    costPrice: 62000,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80'],
    features: ['Google Tensor G3 Processor', '50MP Computational Main Camera', 'Super Actua 120Hz Display'],
    tags: ['smartphone', 'smartphones', 'phone', 'mobile', '5g'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-045',
    storeId,
    name: 'OnePlus Nord Neo 5G Phone',
    description: 'Snapdragon 7 Gen 3, 50MP Sony LYT-600 OIS camera, 80W SUPERVOOC charging, and 5500mAh 4-year health battery.',
    category: 'Mobile',
    brand: 'OnePlus',
    price: 24999,
    costPrice: 19500,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80'],
    features: ['80W SuperVOOC Fast Charge', 'Sony LYT-600 OIS Camera', '5500mAh High-Density Battery'],
    tags: ['smartphone', 'smartphones', 'phone', 'mobile', 'oneplus'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-046',
    storeId,
    name: 'MagSafe Leatherette Magnetic Phone Case',
    description: 'Premium vegan leather phone case with integrated N52 strong magnets compatible with MagSafe accessories.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 899,
    costPrice: 320,
    stock: 70,
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80'],
    features: ['Strong N52 MagSafe Magnets', 'Microfiber Scratch Interior', 'Raised Camera Bezel'],
    tags: ['phone case', 'case', 'cover', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-047',
    storeId,
    name: 'ArmorShield Matte Anti-Glare Screen Guard (2-Pack)',
    description: 'Matte tempered glass that eliminates harsh sun glare and finger oil smudges while preserving touch sensitivity.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 399,
    costPrice: 95,
    stock: 110,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&auto=format&fit=crop&q=80'],
    features: ['Matte Anti-Reflective Finish', 'Oleophobic Smooth Gliding Layer', 'Easy Alignment Frame Included'],
    tags: ['screen protector', 'tempered glass', 'guard', 'accessories', 'phone'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-048',
    storeId,
    name: 'PowerCore 20000mAh 45W Fast Power Bank',
    description: 'High capacity 20,000mAh external battery with 45W USB-C Power Delivery to fast-charge phones, tablets, and ultrabooks.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 2799,
    costPrice: 1400,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['20,000mAh Airline-Approved Capacity', '45W USB-C PD Two-Way Charging', 'Digital Battery Level Display'],
    tags: ['power bank', 'charger', 'battery pack', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-049',
    storeId,
    name: 'MagHold Magnetic Wireless Car Mount Charger',
    description: '15W wireless car charging phone mount with sturdy air vent clamp and strong magnetic locking ring.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 1799,
    costPrice: 780,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['15W Fast Wireless Output', 'One-Hand Magnetic Mounting', '360-Degree Ball Joint'],
    tags: ['car charger', 'car mount', 'phone holder', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-050',
    storeId,
    name: 'Apple iPhone 15 128GB (Blue)',
    description: 'Dynamic Island, 48MP main camera with 2x Telephoto, USB-C connector, and durable color-infused back glass.',
    category: 'Mobile',
    brand: 'Apple',
    price: 69900,
    costPrice: 58000,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80'],
    features: ['Dynamic Island Interface', '48MP Main Camera with 2x Telephoto', 'USB-C Charging & Data', 'A16 Bionic Chip'],
    tags: ['smartphone', 'phone', 'iphone', 'apple', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-051',
    storeId,
    name: 'CrystalClear Slim TPU Phone Case',
    description: 'Non-yellowing crystal clear flexible TPU phone bumper case showing the phone natural color.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 499,
    costPrice: 110,
    stock: 140,
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80'],
    features: ['Anti-Yellowing Bayer TPU', 'Micro-Dot Pattern Prevents Watermarking', 'Slim 1.2mm Profile'],
    tags: ['phone case', 'case', 'cover', 'clear case', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-052',
    storeId,
    name: 'TurboCharge 30W Compact Wall Charger',
    description: 'Single-port 30W USB-C PD fast charger capable of charging phones to 50% in under 25 minutes.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 799,
    costPrice: 280,
    stock: 85,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['30W Power Delivery Fast Charge', 'Multi-Protection Safety Suite', 'Ultra Compact Foldable Pins'],
    tags: ['charger', 'fast charger', 'usb-c', 'power adapter', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-053',
    storeId,
    name: 'FlexGrip Desktop Phone & Tablet Stand',
    description: 'Weighted carbon steel base phone stand with dual articulation pivots for video calls and content consumption.',
    category: 'Accessories',
    brand: 'AlumaStand',
    price: 699,
    costPrice: 250,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['Weighted Anti-Slip Base', 'Reserved Charging Cable Port', 'Dual 270° Angle Adjustments'],
    tags: ['phone stand', 'stand', 'holder', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-054',
    storeId,
    name: 'Braided Lightning to USB-C Cable (1.5m)',
    description: 'MFi-certified nylon braided fast charging cable for iPhone and iPad with reinforced strain relief.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 599,
    costPrice: 190,
    stock: 95,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['MFi Certified Lightning Connector', '20,000+ Bend Tested Strain Relief', 'Fast Power Delivery Support'],
    tags: ['lightning cable', 'charging cable', 'cables', 'accessories', 'iphone'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-055',
    storeId,
    name: 'ArmorShield Privacy Screen Guard for iPhone',
    description: 'Two-way privacy tempered glass preventing side viewing angles beyond 28 degrees in public spaces.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 599,
    costPrice: 180,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&auto=format&fit=crop&q=80'],
    features: ['28° Anti-Peeping Privacy Filter', '9H Shatter-Resistant Glass', 'True Retina Clarity Front-On'],
    tags: ['screen protector', 'privacy screen', 'tempered glass', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-056',
    storeId,
    name: 'MagCharge 3-in-1 Foldable Wireless Charging Station',
    description: 'Simultaneously charges phone, smartwatch, and wireless earbuds with sleek foldable magnetic pads.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 2999,
    costPrice: 1450,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['3-in-1 Simultaneous Charging', 'MagSafe Magnetic Alignment', 'Travel Foldable Silicone Design'],
    tags: ['wireless charger', 'charging station', 'charger', 'accessories', 'mobile'],
    status: 'PUBLISHED',
  },

  // --- TABLETS (prod-057 to prod-063) ---
  {
    id: 'prod-057',
    storeId,
    name: 'NovaPad Pro 11" Creator Tablet',
    description: '11-inch 2.5K 120Hz IPS display, Snapdragon 870, quad stereo speakers, and stylus active pen support.',
    category: 'Tablets',
    brand: 'NovaBook',
    price: 32999,
    costPrice: 24000,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80'],
    features: ['11" 2.5K 120Hz Fluid Display', 'Snapdragon 870 Octa-Core', 'Quad Dolby Atmos Speakers'],
    tags: ['tablet', 'tablets', 'android tablet', 'drawing tablet'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-058',
    storeId,
    name: 'Apple iPad 10th Gen 64GB Wi-Fi',
    description: '10.9-inch Liquid Retina display, A14 Bionic chip, landscape 12MP front camera with Center Stage.',
    category: 'Tablets',
    brand: 'Apple',
    price: 34900,
    costPrice: 28000,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80'],
    features: ['10.9-inch Liquid Retina Display', 'A14 Bionic Processor', 'Touch ID Top Button', 'USB-C Charging'],
    tags: ['tablet', 'tablets', 'ipad', 'apple', 'college tablet'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-059',
    storeId,
    name: 'NovaStylus Active Digital Pen',
    description: '4096 levels of pressure sensitivity, tilt detection, palm rejection, and USB-C rechargeable battery for tablets.',
    category: 'Accessories',
    brand: 'NovaBook',
    price: 2499,
    costPrice: 1100,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80'],
    features: ['4096 Pressure Levels', 'Palm Rejection Technology', 'Magnetic Wireless Attachment'],
    tags: ['stylus', 'digital pen', 'tablet pen', 'accessories', 'tablets'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-060',
    storeId,
    name: 'Smart Magnetic Folio Case for 11" Tablets',
    description: 'Slim lightweight magnetic trifold stand cover with auto wake/sleep functionality and pencil holder clasp.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 1199,
    costPrice: 420,
    stock: 55,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80'],
    features: ['Strong Magnetic Attachment', 'Trifold Typing & Viewing Angles', 'Auto Wake / Sleep Feature'],
    tags: ['tablet case', 'case', 'folio cover', 'accessories', 'tablets'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-061',
    storeId,
    name: 'Magnetic Bluetooth Keyboard Case for 11" iPad',
    description: 'Detachable wireless backlit keyboard with built-in precision multi-touch trackpad and kickstand.',
    category: 'Accessories',
    brand: 'Keychron',
    price: 4299,
    costPrice: 2400,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['Integrated Multi-Touch Trackpad', 'Adjustable White Backlit Keys', 'Detachable Magnetic Keyboard'],
    tags: ['tablet keyboard', 'keyboard case', 'accessories', 'tablets', 'ipad'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-062',
    storeId,
    name: 'PaperFeel Matte Screen Guard for 11" Tablets',
    description: 'Micro-textured matte PET film that replicates the tactile resistance of writing and drawing with paper.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 699,
    costPrice: 220,
    stock: 60,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&auto=format&fit=crop&q=80'],
    features: ['Paper-Like Tactile Drawing Friction', 'Anti-Glare Matte Surface', 'Wear-Resistant PET Film'],
    tags: ['screen protector', 'paperfeel', 'tablet guard', 'accessories', 'tablets'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-063',
    storeId,
    name: 'Heavy-Duty 360 Rotating Tablet Hand Grip Case',
    description: 'Rugged drop-proof case with 360-degree rotating hand strap, kickstand, and detachable shoulder carry strap.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 1699,
    costPrice: 650,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80'],
    features: ['Triple Layer Shock Absorption', '360 Rotating Hand Strap', 'Integrated Pop-Out Kickstand'],
    tags: ['tablet case', 'rugged case', 'protective case', 'accessories', 'tablets'],
    status: 'PUBLISHED',
  },

  // --- GAMING (prod-064 to prod-074) ---
  {
    id: 'prod-064',
    storeId,
    name: 'ViperStrike Pro Wireless Ultralight Gaming Mouse',
    description: '59-gram competition esports mouse with PAW3395 26,000 DPI optical sensor and 4K polling rate capability.',
    category: 'Gaming',
    brand: 'ViperStrike',
    price: 4999,
    costPrice: 2700,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['59g Ultralight Honeycomb Design', 'PAW3395 26K DPI Sensor', 'Optical Micro Switches 90M Clicks'],
    tags: ['gaming mouse', 'mouse', 'gaming', 'esports', 'wireless mouse'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-065',
    storeId,
    name: 'ViperStrike 60% RGB Mechanical Gaming Keyboard',
    description: 'Hot-swappable linear yellow switches, double-shot PBT keycaps, sound dampening foam, and detachable braided USB-C.',
    category: 'Gaming',
    brand: 'ViperStrike',
    price: 3999,
    costPrice: 2100,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&auto=format&fit=crop&q=80'],
    features: ['60% Compact Form Factor', 'Pre-Lubed Linear Switches', '16.8M Per-Key RGB Illumination'],
    tags: ['gaming keyboard', 'mechanical keyboard', 'keyboard', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-066',
    storeId,
    name: 'AudioStrike 7.1 Surround Gaming Headset',
    description: '53mm neodymium directional drivers, memory foam ear cushions, and detachable noise-cancelling broadcast boom mic.',
    category: 'Gaming',
    brand: 'ViperStrike',
    price: 3499,
    costPrice: 1750,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80'],
    features: ['Virtual 7.1 Positional Audio', '53mm Custom Tuned Drivers', 'Detachable Discord-Certified Mic'],
    tags: ['gaming headset', 'headset', 'headphones', 'gaming', 'audio'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-067',
    storeId,
    name: 'NexusPad Wireless Game Controller for PC & Android',
    description: 'Hall effect magnetic joysticks and triggers with zero stick drift, mechanical face buttons, and customizable macro paddles.',
    category: 'Gaming',
    brand: 'NexusPad',
    price: 3299,
    costPrice: 1600,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&auto=format&fit=crop&q=80'],
    features: ['Hall Effect Anti-Drift Sticks', 'Linear Analog Hall Triggers', 'Dual Vibration Rumble Motors'],
    tags: ['controller', 'gamepad', 'gaming controller', 'gaming', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-068',
    storeId,
    name: 'Razer DeathAdder V3 Ergonomic Esports Mouse',
    description: 'Ergonomic shape refined with top esports pros, Focus Pro 30K optical sensor, and ultra-durable optical switches.',
    category: 'Gaming',
    brand: 'Razer',
    price: 5999,
    costPrice: 4200,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['Focus Pro 30K Optical Sensor', 'Speedflex Ultra-Light Cable', 'Gen-3 Optical Mouse Switches'],
    tags: ['gaming mouse', 'razer', 'mouse', 'gaming', 'esports'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-069',
    storeId,
    name: 'Logitech G PRO X Mechanical Gaming Keyboard',
    description: 'Tournament-proven PRO keyboard with user-swappable pro-grade switches and compact tenkeyless design.',
    category: 'Gaming',
    brand: 'Logitech',
    price: 11995,
    costPrice: 8500,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['Tenkeyless Esports Profile', 'User-Swappable Switches', 'LIGHTSYNC RGB Integration'],
    tags: ['gaming keyboard', 'logitech g', 'keyboard', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-070',
    storeId,
    name: 'HyperX Cloud III Wireless Gaming Headset',
    description: 'Up to 120 hours of wireless battery, DTS Headphone:X spatial audio, and redesigned 53mm angled acoustic drivers.',
    category: 'Gaming',
    brand: 'HyperX',
    price: 13990,
    costPrice: 9800,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80'],
    features: ['120 Hours Long Battery', 'Angled 53mm Audio Drivers', 'DTS Spatial Audio Lifetime License'],
    tags: ['gaming headset', 'headset', 'headphones', 'gaming', 'hyperx'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-071',
    storeId,
    name: 'StreamCast 1080p 60FPS Gaming Webcam with Ring Light',
    description: 'Full HD 60fps streaming camera with integrated multi-level adjustable LED ring light and autofocus.',
    category: 'Accessories',
    brand: 'ClearCam',
    price: 3899,
    costPrice: 1900,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80'],
    features: ['1080p @ 60FPS Video Capture', 'Touch-Controlled LED Ring Light', 'Wide 86° Field of View'],
    tags: ['webcam', 'streaming', 'gaming camera', 'accessories', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-072',
    storeId,
    name: 'SpeedPro RGB Extended Gaming Mouse Pad',
    description: '900x350mm micro-textured cloth speed surface with 14 customizable RGB spectrum border lighting modes.',
    category: 'Accessories',
    brand: 'ViperStrike',
    price: 1299,
    costPrice: 550,
    stock: 60,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['14 Dynamic RGB Lighting Modes', 'Micro-Textured Speed Weave', 'Anti-Slip Rubber Base'],
    tags: ['mouse pad', 'gaming mouse pad', 'accessories', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-073',
    storeId,
    name: 'HeadsetStand RGB with Dual USB 3.0 Hub',
    description: 'Aluminum headset hanger with non-slip weighted base, RGB lighting effects, and 2x USB pass-through ports.',
    category: 'Accessories',
    brand: 'ViperStrike',
    price: 1499,
    costPrice: 620,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Dual USB 3.0 Expansion Ports', 'RGB Ambient Base Glow', 'Sturdy Aluminum Support Bar'],
    tags: ['headset stand', 'stand', 'accessories', 'gaming'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-074',
    storeId,
    name: 'Tactile Grip Gaming Mouse Cable Bungee',
    description: 'Rust-resistant spring arm that keeps mouse cables elevated for drag-free wireless-like mouse control.',
    category: 'Accessories',
    brand: 'ViperStrike',
    price: 599,
    costPrice: 200,
    stock: 70,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['Drag-Free Cord Control', 'Heavy Weighted Base with Suction', 'Flexible Silicon Cable Catch'],
    tags: ['mouse bungee', 'accessories', 'gaming', 'mouse'],
    status: 'PUBLISHED',
  },

  // --- MONITORS (prod-075 to prod-082) ---
  {
    id: 'prod-075',
    storeId,
    name: 'ViewMaster 27" QHD 180Hz Gaming Monitor',
    description: '27-inch 2560x1440 Fast IPS panel, 180Hz refresh rate, 0.5ms response time, AMD FreeSync Premium, and HDR400.',
    category: 'Monitors',
    brand: 'ViewMaster',
    price: 19999,
    costPrice: 14800,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['27" QHD 2560x1440 Fast IPS', '180Hz Ultra-Fluid Refresh Rate', '0.5ms MPRT Response Time', 'AMD FreeSync Premium'],
    tags: ['monitor', 'monitors', 'gaming monitor', 'qhd monitor', 'display'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-076',
    storeId,
    name: 'ViewMaster 34" Curved WQHD Ultrawide Monitor',
    description: '34-inch 3440x1440 1500R curved ultrawide 21:9 display, 165Hz refresh, sRGB 120%, ideal for gaming and productivity.',
    category: 'Monitors',
    brand: 'ViewMaster',
    price: 32999,
    costPrice: 24500,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['34" 21:9 WQHD 3440x1440', '1500R Immersive Curvature', '165Hz Refresh Rate', 'Picture-by-Picture Multitasking'],
    tags: ['monitor', 'monitors', 'ultrawide monitor', 'gaming monitor', 'display'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-077',
    storeId,
    name: 'ProArt 27" 4K UHD Colorist Monitor',
    description: 'Factory calibrated Delta E < 2 color accuracy, 99% DCI-P3, USB-C 90W power delivery single-cable workstation display.',
    category: 'Monitors',
    brand: 'NovaBook',
    price: 38999,
    costPrice: 29000,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['27" 4K UHD 3840x2160 IPS', '99% DCI-P3 Color Gamut', '90W USB-C Video & PD Charging', 'Ergonomic Stand with Pivot'],
    tags: ['monitor', 'monitors', '4k monitor', 'office monitor', 'creator monitor'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-078',
    storeId,
    name: 'ClearView 24" FHD 100Hz Office Monitor',
    description: 'Borderles 24-inch 1920x1080 IPS panel with TÜV Rheinland eye comfort low blue light certification and built-in speakers.',
    category: 'Monitors',
    brand: 'ClearView',
    price: 7999,
    costPrice: 5400,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['24" FHD 1920x1080 IPS Panel', '100Hz Smooth Eye-Care Refresh', 'Low Blue Light & Flicker-Free'],
    tags: ['monitor', 'monitors', 'office monitor', 'budget monitor', 'display'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-079',
    storeId,
    name: 'FlexArm Heavy-Duty Single Monitor Desk Mount',
    description: 'Gas spring counterbalance articulating monitor arm supporting screens up to 32 inches and 9kg with cable management.',
    category: 'Accessories',
    brand: 'AlumaStand',
    price: 2499,
    costPrice: 1100,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['Gas Spring Counterbalance System', 'VESA 75x75 and 100x100 Compatible', 'Integrated Cable Concealment Channels'],
    tags: ['monitor arm', 'monitor mount', 'stand', 'accessories', 'monitors'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-080',
    storeId,
    name: 'ScreenBar Eye-Care Auto-Dimming Monitor Light Bar',
    description: 'Asymmetric optical light bar that mounts atop monitors, illuminating desks with zero screen glare and touch dimming.',
    category: 'Accessories',
    brand: 'AlumaStand',
    price: 2899,
    costPrice: 1300,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    features: ['Asymmetric Optical Anti-Glare Design', 'Adjustable Color Temperatures (2800K-6500K)', 'USB Powered Touch Bar'],
    tags: ['screenbar', 'monitor light', 'desk lamp', 'accessories', 'monitors'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-081',
    storeId,
    name: 'UltraSpeed 8K HDMI 2.1 Braided Cable (2m)',
    description: 'Certified 48Gbps ultra high speed HDMI 2.1 cable supporting 8K 60Hz and 4K 120Hz with eARC and dynamic HDR.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 799,
    costPrice: 280,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['48Gbps Bandwidth HDMI 2.1', 'Supports 4K @ 120Hz & 8K @ 60Hz', 'Heavy-Duty Zinc Alloy Shells'],
    tags: ['hdmi cable', 'cables', 'accessories', 'monitors'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-082',
    storeId,
    name: 'HighSpeed DisplayPort 1.4 Cable (2m)',
    description: 'VESA certified 32.4Gbps DisplayPort 1.4 cable with latching connectors, supporting 4K 144Hz and 2K 240Hz.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 699,
    costPrice: 240,
    stock: 85,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['32.4Gbps DP 1.4 Standard', 'Supports 2K @ 240Hz & 4K @ 144Hz', 'Secure Latching Gold-Plated Tips'],
    tags: ['displayport cable', 'cables', 'accessories', 'monitors'],
    status: 'PUBLISHED',
  },

  // --- STORAGE (prod-083 to prod-089) ---
  {
    id: 'prod-083',
    storeId,
    name: 'SpeedDrive 1TB NVMe PCIe 4.0 Internal SSD',
    description: 'Blazing read speeds up to 7400MB/s, M.2 2280 form factor, compatible with PCs, laptops, and PlayStation 5.',
    category: 'Storage',
    brand: 'SpeedDrive',
    price: 6999,
    costPrice: 4800,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    features: ['PCIe Gen4 x4 Interface', '7400MB/s Sequential Read Speed', 'Integrated Graphene Thermal Pad'],
    tags: ['ssd', 'nvme ssd', 'internal ssd', 'storage', 'fast storage'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-084',
    storeId,
    name: 'RuggedVault 2TB Portable External SSD',
    description: 'IP65 water and dust resistant USB 3.2 Gen2 portable SSD with 1050MB/s read/write speeds in shockproof rubber bumper.',
    category: 'Storage',
    brand: 'SpeedDrive',
    price: 13999,
    costPrice: 9800,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    features: ['1050MB/s Read & 1000MB/s Write', 'IP65 Dust and Water Resistant', '3-Meter Drop Protection Bumper'],
    tags: ['external ssd', 'portable ssd', 'storage', 'backup', 'usb-c'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-085',
    storeId,
    name: 'DataSafe 4TB USB 3.0 External Hard Drive',
    description: 'High capacity 2.5" portable HDD formatted for Windows and Mac with automated backup software.',
    category: 'Storage',
    brand: 'DataSafe',
    price: 8499,
    costPrice: 6100,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    features: ['4TB Massive Storage Capacity', 'USB 3.0 High-Speed Transfer', 'Includes Automated Backup Utility'],
    tags: ['hard drive', 'external hdd', 'storage', 'backup'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-086',
    storeId,
    name: 'UltraFlash 128GB Dual USB-C & USB-A Flash Drive',
    description: 'Swiveling all-metal flash drive that transfers files effortlessly between smartphones, tablets, and computers.',
    category: 'Storage',
    brand: 'SpeedDrive',
    price: 1199,
    costPrice: 480,
    stock: 90,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    features: ['Dual USB-C and USB-A Connectors', '150MB/s Read Speeds', 'All-Metal 360 Swivel Body'],
    tags: ['pen drive', 'usb drive', 'flash drive', 'storage', 'usb-c'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-087',
    storeId,
    name: 'ProExtreme 256GB MicroSDXC Card with Adapter',
    description: 'U3, V30, A2 rated memory card optimized for 4K video recording, drones, action cameras, and Nintendo Switch.',
    category: 'Storage',
    brand: 'SpeedDrive',
    price: 1999,
    costPrice: 850,
    stock: 75,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    features: ['190MB/s Read and 130MB/s Write', 'V30 4K UHD Video Speed Class', 'A2 Rated for Rapid App Loading'],
    tags: ['sd card', 'microsd', 'memory card', 'storage', 'camera'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-088',
    storeId,
    name: 'AlumaVault M.2 NVMe SSD Tool-Free Enclosure',
    description: '10Gbps USB 3.2 Gen2 aluminum enclosure with silicone heatsink, turns any M.2 NVMe SSD into a portable drive.',
    category: 'Accessories',
    brand: 'OmniPort',
    price: 1899,
    costPrice: 820,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['10Gbps USB 3.2 Gen2 Speed', '100% Tool-Free Installation Push Lock', 'All-Aluminum Grooved Heat Sink'],
    tags: ['ssd enclosure', 'm.2 enclosure', 'accessories', 'storage'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-089',
    storeId,
    name: 'Protective Shockproof Storage Case for Hard Drives',
    description: 'Molded EVA hard shell travel case with internal mesh pocket for cables and 2.5" external drives.',
    category: 'Accessories',
    brand: 'ArmorPack',
    price: 499,
    costPrice: 150,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80'],
    features: ['Drop-Resistant EVA Hard Shell', 'Internal Elastic Securing Strap', 'Mesh Cable Accessory Pocket'],
    tags: ['case', 'storage case', 'hard drive case', 'accessories'],
    status: 'PUBLISHED',
  },

  // --- NETWORKING (prod-090 to prod-095) ---
  {
    id: 'prod-090',
    storeId,
    name: 'ArcherSpeed AX3000 Wi-Fi 6 Gigabit Router',
    description: 'Dual-band Wi-Fi 6 speeds up to 3000Mbps, 4 high-gain antennas with beamforming, OFDMA, and WPA3 security.',
    category: 'Networking',
    brand: 'ArcherSpeed',
    price: 3999,
    costPrice: 2600,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['3 Gbps Dual Band Wi-Fi 6', '4 High-Gain Antennas with Beamforming', 'Gigabit WAN and 4x Gigabit LAN Ports'],
    tags: ['wifi router', 'router', 'wifi 6', 'networking', 'internet'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-091',
    storeId,
    name: 'MeshLink Home Whole-Home Wi-Fi 6 Mesh System (2-Pack)',
    description: 'Seamless whole-home roaming coverage up to 4,000 sq.ft with intelligent AI mesh traffic prioritization.',
    category: 'Networking',
    brand: 'ArcherSpeed',
    price: 8999,
    costPrice: 6100,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Covers up to 4000 Sq. Ft.', 'Seamless Roaming Under Single SSID', 'Handles 120+ Simultaneous Devices'],
    tags: ['mesh wifi', 'router', 'networking', 'wifi system'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-092',
    storeId,
    name: 'SpeedLink USB 3.0 to Gigabit Ethernet Adapter',
    description: 'Compact aluminum USB-A to RJ45 network adapter giving laptops instant 1000Mbps wired internet connectivity.',
    category: 'Accessories',
    brand: 'OmniPort',
    price: 899,
    costPrice: 320,
    stock: 65,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['1000Mbps Gigabit Transfer', 'Driver-Free Plug & Play', 'Aluminum Heat Dissipating Shell'],
    tags: ['ethernet adapter', 'usb ethernet', 'networking', 'accessories', 'laptop'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-093',
    storeId,
    name: 'Cat7 Shielded Flat Gigabit Ethernet Cable (5m)',
    description: 'High performance Cat7 flat network cable with gold-plated shielded RJ45 connectors, supporting 10Gbps 600MHz.',
    category: 'Accessories',
    brand: 'OmniPort',
    price: 499,
    costPrice: 160,
    stock: 100,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['10Gbps High-Speed Bandwidth', 'Flat Design Slips Under Carpets and Doors', 'Gold-Plated Shielded Connectors'],
    tags: ['ethernet cable', 'network cable', 'cables', 'accessories', 'networking'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-094',
    storeId,
    name: 'Wi-Fi 6 Dual Band USB Wireless Adapter',
    description: 'High-gain dual 5dBi antenna USB 3.0 Wi-Fi 6 dongle upgrade for desktop computers and laptops.',
    category: 'Networking',
    brand: 'ArcherSpeed',
    price: 1799,
    costPrice: 850,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Wi-Fi 6 1800Mbps Dual Band', 'Dual 5dBi High Gain Antennas', 'WPA3 Advanced Wireless Encryption'],
    tags: ['wifi adapter', 'wifi dongle', 'networking', 'wireless'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-095',
    storeId,
    name: '5-Port Gigabit Desktop Ethernet Switch',
    description: 'Plug-and-play fanless metal housing gigabit desktop switch for home offices and gaming rooms.',
    category: 'Networking',
    brand: 'ArcherSpeed',
    price: 1399,
    costPrice: 650,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['5 Auto-Negotiation Gigabit Ports', 'Silent Fanless Sturdy Metal Casing', 'Green Ethernet Power Savings'],
    tags: ['ethernet switch', 'network switch', 'networking'],
    status: 'PUBLISHED',
  },

  // --- DESK ACCESSORIES & ESSENTIALS (prod-096 to prod-100) ---
  {
    id: 'prod-096',
    storeId,
    name: 'Silicone Cable Organizer Management Clips (5-Pack)',
    description: 'Eco-friendly self-adhesive silicone desktop cord holders that keep charging and peripheral cables organized.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 299,
    costPrice: 60,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    features: ['Reusable 3M Sticky Adhesive Backing', 'Flexible Soft Silicone Slots', 'Universal Cable Compatibility'],
    tags: ['cable organizer', 'cable clips', 'accessories', 'desk accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-097',
    storeId,
    name: 'Precision Electronics 7-in-1 Cleaning Kit',
    description: 'Multifunctional cleaning pen for earbuds, keycap puller, microfiber screen spray, and brush for keyboards and phones.',
    category: 'Accessories',
    brand: 'ArmorShield',
    price: 349,
    costPrice: 85,
    stock: 130,
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80'],
    features: ['Foldable Earbuds Cleaning Tip', 'Mechanical Keyboard Keycap Remover', 'Refillable Screen Spray Bottle'],
    tags: ['cleaning kit', 'cleaner', 'accessories', 'earbuds cleaner'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-098',
    storeId,
    name: 'OmniPlug 4-Way Surge Protector Power Strip with 20W USB-C',
    description: 'Heavy duty fire-retardant extension board with 4 universal AC sockets, 20W USB-C Power Delivery, and surge suppression.',
    category: 'Accessories',
    brand: 'TurboCharge',
    price: 1599,
    costPrice: 720,
    stock: 55,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    features: ['1050 Joules Surge Protection', '20W USB-C PD Fast Port', 'Flame-Retardant ABS Enclosure (750°C)'],
    tags: ['power strip', 'surge protector', 'extension cord', 'accessories'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-099',
    storeId,
    name: 'ErgoRest Memory Foam Keyboard & Mouse Wrist Rest Set',
    description: 'Ergonomic high-density slow-rebound memory foam wrist cushions wrapped in breathable Lycra fabric.',
    category: 'Accessories',
    brand: 'GlidePro',
    price: 899,
    costPrice: 310,
    stock: 70,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80'],
    features: ['Ergonomic Contoured Relief Shape', 'Non-Skid Textured Rubber Base', 'Slow-Rebound Memory Foam Core'],
    tags: ['wrist rest', 'ergonomic', 'accessories', 'keyboard wrist rest'],
    status: 'PUBLISHED',
  },
  {
    id: 'prod-100',
    storeId,
    name: 'OmniMount Universal Headphone Desk Clamp Hanger',
    description: '360-degree rotating under-desk headphone holder with built-in cable loop and soft rubber clamping pads.',
    category: 'Accessories',
    brand: 'AlumaStand',
    price: 649,
    costPrice: 220,
    stock: 85,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'],
    features: ['360° Rotating Arm', 'Spring Clamp Fits Desks Up to 40mm', 'Integrated Cable Loop Organizer'],
    tags: ['headphone stand', 'headphone hanger', 'accessories', 'desk accessories'],
    status: 'PUBLISHED',
  },
];
